// document action-types
export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
export const VIEW_DOCUMENTS = 'VIEW_DOCUMENTS';
export const EDIT_DOCUMENT = 'EDIT_DOCUMENT';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const VIEW_ONE_DOCUMENT = 'VIEW_ONE_DOCUMENT';
export const VIEW_OWN_DOCUMENTS = 'VIEW_OWN_DOCUMENTS';

// document error action types
export const CREATE_DOCUMENT_ERROR = 'CREATE_DOCUMENT_ERROR';
export const VIEW_DOCUMENTS_ERROR = 'VIEW_DOCUMENTS_ERROR';
export const EDIT_DOCUMENT_ERROR = 'EDIT_DOCUMENT_ERROR';
export const DELETE_DOCUMENT_ERROR = 'DELETE_DOCUMENT_ERROR';
export const CHANGE_CURRENT_DOCUMENT = 'CHANGE_CURRENT_DOCUMENT';
export const SEARCH_DOCUMENT = 'SEARCH_DOCUMENT';
export const SEARCH_DOCUMENT_ERROR = 'SEARCH_DOCUMENT_ERROR';
export const VIEW_ONE_DOCUMENT_ERROR = 'VIEW_ONE_DOCUMENT_ERROR';
export const VIEW_OWN_DOCUMENTS_ERROR = 'VIEW_OWN_DOCUMENTS_ERROR';

// user action types
export const CREATE_USER = 'CREATE_USER';
export const VIEW_USERS = 'VIEW_USERS';
export const SIGNIN_USER = 'SIGNIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CHANGE_CURRENT_PROFILE = 'CHANGE_CURRENT_PROFILE';
export const SEARCH_USERS = 'SEARCH_USERS';
export const UPDATE_USER = 'UPDATE_USER';

// user error action types
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const SIGNIN_USER_ERROR = 'SIGNIN_USER_ERROR';
export const VIEW_USERS_ERROR = 'VIEW_USERS_ERROR';
export const SEARCH_USERS_ERROR = 'SEARCH_USERS_ERROR';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
